language: java
jdk:
  - oraclejdk8
after_success:
  - ./gradlew cobertura coveralls
notifications:
  slack:
    rooms:
      - kingsskiclub:BBL9dzzOo8JFgSqRupOaxr4p#software-integrations
    template:
      - "%{repository_slug} (%{commit}) to %{branch} by %{author} : %{result}"
      - "Build details: %{build_url}"
